name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container:
      image: oracle/graalvm-ce:20.2.0-java11
    steps:
      - name: Install native-image
        run: gu install native-image
      - name: Get location of maven local repository
        id: maven-cache
        run: |
          echo "::set-output name=dir::$(mvn help:evaluate -Dexpression=settings.localRepository | grep -v INFO)"
      - name: Restore cache of maven local repository
        uses: actions/cache@v2
        with:
          path: ${{ steps.maven-cache.output.dir }}
          key: .m2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with Maven
        run: ./mvnw package
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: rand-${{ matrix.os }}
          path: target/rand