name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    needs: prepare
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    container:
      image: oracle/graalvm-ce:20.2.0-java11
    steps:
      - name: Install native-image
        run: |
          gu install native-image
      - name: Restore cache of maven local repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with Maven
        run: |
          ./mvnw verify -Dnative.skip=false
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: rand-${{ matrix.os }}
          path: target/rand
      - name: Slack notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}