name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container:
      image: oracle/graalvm-ce:20.2.0-java11
    steps:
      - name: Install native-image
        run: gu install native-image
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with Maven
        run: ./mvnw package
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: rand-${{ matrix.os }}
          path: target/rand